config/routes.rb
Rails.application.routes.draw do
  resources :parisbis

  root 'pages#home'

  devise_for :users

  # route pour link to action user admin
  resources :users do
    member do
      get :toggle_status
    end
  end


  resources :friends
  resources :saisons
  resources :divisions
  resources :circuits
  resources :events
  resources :equipes
  resources :pilotes
  resources :resultats
  resources :classecuries
  resources :parieurs


  resources :classements do
    member do
      get :toggle_creerclassements
      get :toggle_updateclassements
      get :toggle_supprimerclassements
      get :toggle_triclassements
    end
  end

  resources :cotes do
    member do
      get :toggle_calculcotes
      get :cote_victoire
    end
  end


  resources :paris do
    member do
      get :toggle_calculresultats
    end
  end

  resources :pariquarts do
    member do
      get :toggle_calculresultats
    end
  end


  get 'home/index'
  get 'home/users'
  get 'home/role'


  # test call action
  resources :licences do
    member do
      get :toggle_creerlicences
      get :toggle_supprimerlicences
      get :toggle_calculrecuplicences
      get :toggle_calculrecuplicencesIndiv
  
    end
  end

end

app/models/classement.rb
class Classement < ApplicationRecord
  #  has_many :events, through: :resultats
  belongs_to :event, :optional => true
  #before_validation :toggle_creerclassements
  #include Sluggable;

 # has_many :resultats, :dependent => :delete_all 

 scope :event_courant, -> (event_courant) { where("event_id = ?", event_courant)}
 
 scope :saison_courant, -> (saison_courant) { joins(:event).where("saison_id = ?", saison_courant)}
 scope :division_courant, -> (division_courant) { joins(:event).where("division_id = ?", division_courant)}
 scope :numero_until_courant, -> (numero_until_courant) { joins(:event).where("numero <= ?", numero_until_courant)}

 scope :order_by_score, -> { order('score').reverse }

 # test scopes p1, p2 etc pour ranking
scope :compte_p1, -> { where("(course) = 1").count}
scope :compte_p2, -> { where("(course) = 2").count}
scope :compte_p3, -> { where("(course) = 3").count}
scope :compte_p4, -> { where("(course) = 4").count}
scope :compte_p5, -> { where("(course) = 5").count}
scope :compte_p6, -> { where("(course) = 6").count}
scope :compte_p7, -> { where("(course) = 7").count}
scope :compte_p8, -> { where("(course) = 8").count}
scope :compte_p9, -> { where("(course) = 9").count}
scope :compte_p10, -> { where("(course) = 10").count}
scope :compte_p11, -> { where("(course) = 11").count}
scope :compte_p12, -> { where("(course) = 12").count}
scope :compte_p13, -> { where("(course) = 13").count}
scope :compte_p14, -> { where("(course) = 14").count}
scope :compte_p15, -> { where("(course) = 15").count}
scope :compte_p16, -> { where("(course) = 16").count}
scope :compte_p17, -> { where("(course) = 17").count}
scope :compte_p18, -> { where("(course) = 18").count}
scope :compte_p19, -> { where("(course) = 19").count}
scope :compte_p20, -> { where("(course) = 20").count}
# continuer ajouter les autres compte p x


scope :order_score_positions, 
      -> {order(score: :DESC, compte_p1: :DESC, compte_p2: :DESC, compte_p3: :DESC, compte_p4: :DESC, compte_p5: :DESC,
                              compte_p6: :DESC, compte_p7: :DESC, compte_p8: :DESC, compte_p9: :DESC, compte_p10: :DESC,
                              compte_p11: :DESC, compte_p12: :DESC, compte_p13: :DESC, compte_p14: :DESC, compte_p15: :DESC,
                              compte_p16: :DESC, compte_p17: :DESC, compte_p18: :DESC, compte_p19: :DESC, compte_p20: :DESC ) }

# continuer ajouter les autres compte p x


 scope :max_points, -> { all.order(score: :DESC).first }


end

app/controllers/classements_controller.rb
class ClassementsController < ApplicationController
  before_action :set_classement, only: %i[ show edit update destroy ]

  def index
    @classements = Classement.all
    @divisions = Division.all
    @events = Event.all
    @saisons = Saison.all
    @pilotes = Pilote.all
    @resultats = Resultat.all
    @resultatsFiltres = Resultat.all

    @resultat = Resultat.all

    @q = Classement.ransack(params[:q])

    if params[:saisonId]
      @saisonId = params[:saisonId]
    end

    if params[:divisionId]
      @divisionId = params[:divisionId]

      @eventsFiltres = @events.where('saison_id = :saison_id AND division_id = :division_id',
        saison_id: @saisonId, division_id: @divisionId)
    end
  
    if params[:eventId]
      @eventId = params[:eventId]
      @eventNum = Event.find(@eventId).numero 

      @divisionId = Event.find(@eventId).division_id 
    
     @classements = Classement.event_courant(@eventId).order_score_positions

    else
      
      @resultats = Resultat.all
      @resultatsFiltres = Resultat.all
      @pilotesActifDiv = Pilote.all
    end

    respond_to do |format|
      format.html
      format.pdf do

       render pdf: "classementPilotes", template: "classements/liste", formats: [:html], layout: "pdf"
      end
    end
    
end

def show
end

def destroy

  @classement.destroy

  respond_to do |format|
    format.html { redirect_to classements_url, notice: "classement was successfully destroyed." }
    format.json { head :no_content }
  end
end

def toggle_creerclassements
  @eventId = params[:id]
  @divisionId = Event.find(@eventId).division_id
  @saisonLiee = Event.find(@eventId).saison_id
  @numGp = Event.find(@eventId).numero 

  @pilotes = Pilote.statut_actif.division_courant(@divisionId).all
    @pilotes.all.each do |pilote|
      classement = Classement.create(pilote_id: pilote.id, event_id: @eventId)
    end
  
  redirect_to classements_url(saisonId: @saisonLiee, eventId: @eventId, divisionId: @divisionId, numGp: @numGp), 
                notice: "les classements ont bien été créés"
end

def toggle_supprimerclassements
  @eventId = params[:id]
  @divisionId = Event.find(@eventId).division_id
  @saisonId = Event.find(@eventId).saison_id

  Classement.where(event_id: @eventId).destroy_all

  redirect_to classements_url(saisonId: @saisonId, eventId: @eventId, divisionId: @divisionId),
               notice: "les classements de l'event courant ont bien été supprimés"
end

def toggle_updateclassements
  @eventId = params[:id]
  @divisionId = Event.find(@eventId).division_id
  @saisonId = Event.find(@eventId).saison_id
  @numGp = Event.find(@eventId).numero 


  @classementsEvent = Classement.all.where(event_id: @eventId)
  
    @classementsEvent.each do |classement|
      @piloteId = classement.pilote_id

      # obtenir le score total du pilote, ajouter les filtres les uns apres les autres
      valScore = Resultat.pilote_courant(@piloteId).division_courant(@divisionId).saison_courant(@saisonId).numero_until_courant(@numGp).sum(:score)
    #  valCoteBase = max_points - valScore

      classement.update(score: valScore )
      
    end

  redirect_to classements_url(saisonId: @saisonId, eventId: @eventId, divisionId: @divisionId, numGp: @numGp), 
                notice: "les classements ont bien été mis à jour"
end

def toggle_triclassements
  @eventId = params[:id]
  @divisionId = Event.find(@eventId).division_id
  @saisonId = Event.find(@eventId).saison_id
  @numGp = Event.find(@eventId).numero 

  max_points = Classement.saison_courant(@saisonId).division_courant(@divisionId).numero_until_courant(@numGp).max_points.score.to_i

  @classementsEvent = Classement.event_courant(@eventId).order_score_positions

    @classementsEvent.each_with_index do |classement, i|
      i = i + 1
      valPosition = i 
      valScore = classement.score
      valCoteBase = 1 + (((max_points - valScore)/100) * i )

      classement.update(position:  valPosition)
      classement.update(cote_victoire:  valCoteBase + 1.4)
      classement.update(cote_podium:  valCoteBase + 0.9 )
      classement.update(cote_top10:  valCoteBase + 0.3)
    end

  redirect_to classements_url(saisonId: @saisonId, eventId: @eventId, divisionId: @divisionId, numGp: @numGp), 
                notice: "les classements ont bien été triés"
end

  private

    def set_classement
      @classement = Classement.find(params[:id])
    end

    def classement_params
     # params.fetch(:classement, {})
     params.require(:classement).permit(:cote, :pilote_id, :event_id)
    end

end

app/views/classements/index.html.erb
<% if user_signed_in? %>
  <h1>Classements Pilotes</h1>  <br/>

  <%= render "shared/choixevent" %>


  <% if (@eventId).present? %>

   <% @eventNum = Event.find(@eventId).numero %>
   <% @divisionId = Event.find(@eventId).division_id %> 
   <% @saisonId = Event.find(@eventId).saison_id %>

    <%# tempo test val max %>
    
  <% @numGp = Event.find(@eventId).numero   %>


    <%= render "shared/eventactif" %>

    <%# boutons crea classement %>

    <%= link_to "Créer classement", toggle_creerclassements_classement_path(@eventId), class:"btn btn-warning", style:"margin: 2px"  %>
    <%= link_to "Update classement", toggle_updateclassements_classement_path(@eventId), class:"btn btn-primary", style:"margin: 2px" %>
    <%= link_to "Supprimer classement", toggle_supprimerclassements_classement_path(@eventId), class:"btn btn-danger", style:"margin: 2px"%>

   <%= link_to "Trier classement", toggle_triclassements_classement_path(@eventId), class:"btn btn-secondary", style:"margin: 2px"%>
 
   <br><br>



    <%#= max points : <%= Classement.saison_courant(@saisonId).division_courant(@divisionId).numero_until_courant(@numGp).max_points.score.to_i %>
    <%#= tableau data classement %>

    <table class="table table-striped table-bordered table-hover">
      <thead class="table-dark">
        <tr>
          <th style="text-align: center;">#</th>
          <th>Pilote</th>
          <th style="text-align: center;">total</th>

        </tr>
      </thead>

      <tbody>
        <tr>
          <% @classements.each do | classement | %>
            <td>  <%= classement.position %></td>
            <td> <%= Pilote.find(classement.pilote_id).nom %>  </td>
            <td>  <%= classement.score %>  </td>
           
        </tr>
        <% end %>
      </tbody>
    </table>

  <br/> <hr/>
        
    <%# PDF event actif %>
    <% numGp = Event.find(@eventId).numero %>
    <%= link_to "PDF",  classements_path(saisonId: @saisonId, divisionId: @divisionId, eventId: @eventId, numGp: numGp, format: :pdf), class:"btn btn-dark" %>

   <% end %>

<% else %>
  <br/>   <strong>Vous n'avez pas les droits...</strong>
<% end %>

app/views/classements/liste.html.erb
<br/>
<h1> Classement Pilotes </h1>
<br/>

<%# haut de page depuis partial %>
<%= render "shared/hautpdf" %>

<%#= tableau data classement %>

 <% if (@eventId).blank? %>
 <% else %>
  <% eventNum = Event.find(@eventId).numero %>
    
      <table style="margin-left:auto;margin-right:auto">
        <thead class="table-dark">
          <tr>
            <th>#</th>
            <th>Pilote</th>
            <th>Points</th>
          </tr>
        </thead>

           <tbody>
        <tr>
          <% @classements.each do | classement | %>
            <td>  <%= classement.position %></td>
            <td> <%= Pilote.find(classement.pilote_id).nom %>  </td>
            <td>  <%= classement.score %>  </td>
           
        </tr>
        <% end %>
      </tbody>
      
  </table>

  <br/>

<%# bas de page depuis partial %>
<%= render "shared/baspdf" %>

<% end %>