config/routes.rb
Rails.application.routes.draw do
  resources :parisbis

  root 'pages#home'

  devise_for :users

  # route pour link to action user admin
  resources :users do
    member do
      get :toggle_status
    end
  end


  resources :friends
  resources :saisons
  resources :divisions
  resources :circuits
  resources :events
  resources :equipes
  resources :pilotes
  resources :resultats
  resources :classecuries
  resources :parieurs


  resources :classements do
    member do
      get :toggle_creerclassements
      get :toggle_updateclassements
      get :toggle_supprimerclassements
      get :toggle_triclassements
    end
  end

  resources :cotes do
    member do
      get :toggle_calculcotes
      get :cote_victoire
    end
  end


  resources :paris do
    member do
      get :toggle_calculresultats
    end
  end

  resources :pariquarts do
    member do
      get :toggle_calculresultats
    end
  end


  get 'home/index'
  get 'home/users'
  get 'home/role'


  # test call action
  resources :licences do
    member do
      get :toggle_creerlicences
      get :toggle_supprimerlicences
      get :toggle_calculrecuplicences
      get :toggle_calculrecuplicencesIndiv
  
    end
  end

end

app/models/resultat.rb
class Resultat < ApplicationRecord

  enum positions: {1 => 1, 2 => 2, 3 => 3, 4 => 4, 5 => 5, 
                     6 => 6, 7 => 7, 8 => 8, 9 => 9, 10 => 10,
                     11 => 11, 12 => 12, 13 => 13, 14 => 14, 15 => 15,
                     16 => 16, 17 => 17, 18 => 18, 19 => 19, 20 => 20
    }

    belongs_to :pilote, :optional => true
    belongs_to :event, :optional => true
    belongs_to :saison, :optional => true

    validates :pilote_id, presence: true
    validates :ecurie, presence: true



    scope :with_mt, -> { where("(mt) = true") }

scope :division_courant, -> (division_courant) { joins(:event).where("division_id = ?", division_courant)}
scope :saison_courant, -> (saison_courant) { joins(:event).where("saison_id = ?", saison_courant)}
scope :event_courant, -> (event_courant) { where("event_id = ?", event_courant)}

scope :pilote_courant, -> (pilote_courant) { where("pilote_id = ?", pilote_courant)}

scope :numero_until_courant, -> (numero_until_courant) { joins(:event).where("numero <= ?", numero_until_courant)}


# test scopes p1, p2 etc pour ranking
scope :compte_p1, -> { where("(course) = 1").count}
scope :compte_p2, -> { where("(course) = 2").count}
scope :compte_p3, -> { where("(course) = 3").count}
scope :compte_p4, -> { where("(course) = 4").count}
scope :compte_p5, -> { where("(course) = 5").count}


scope :order_score_positions, -> {order('score') }

# tempo
scope :group_by_pilote, -> { group('pilote_id') }
scope :sum_by_pilote, -> { sum('score') }
scope :order_by_sum, -> { order('score').reverse }
scope :sum_order_score, -> { select('pilote_id, score, SUM(score) AS total')}

# utilisée
scope :group_sum_order, -> { select('pilote_id, SUM(score) AS total').group('pilote_id').order('total').reverse }
  



end

app/controllers/resultats_controller.rb
class ResultatsController < ApplicationController
  before_action :set_resultat, :formatted_name2, only: %i[ show edit update destroy ]



  # GET /resultats or /resultats.json
  def index
    @classements = Classement.all
    @saisons = Saison.all
    @divisions = Division.all
    @events = Event.all
    @pilotes = Pilote.all
    @resultats = Resultat.all
    @resultatsFiltres = Resultat.all
    
    @resultat = Resultat.all


    if params[:saisonId]
      @saisonId = params[:saisonId]
    end

    if params[:divisionId]
      @divisionId = params[:divisionId]

      @eventsFiltres = @events.where('saison_id = :saison_id AND division_id = :division_id',
        saison_id: @saisonId, division_id: @divisionId)
    end

  
    if params[:eventId]
      @eventId = params[:eventId]
      @eventNum = Event.find(@eventId).numero 

     @resultatsFiltres = Resultat.joins(:event).where(
         'event_id = :event_id',
          event_id: @eventId)
        
     @resultatsFiltres = @resultatsFiltres.order(:course)

      @divisionId = Event.find(@eventId).division_id 

      @pilotes = Pilote.all
      @pilotesActifDiv = Pilote.all.where(statut: "actif", division_id: @divisionId) 
      #@resultatsMaxNumGp = @resultats.all.where('event_id: <=' @eventId) 
      
    else
      
      @resultats = Resultat.all
      @resultatsFiltres = Resultat.all
      @pilotesActifDiv = Pilote.all
    end

    @q = Resultat.ransack(params[:q])
    @resultats = @q.result(distinct: true)



    respond_to do |format|
      format.html
      format.pdf do

       render pdf: "resultats", template: "resultats/liste", formats: [:html], layout: "pdf"
      end
    end

  end

  # GET /resultats/1 or /resultats/1.json
  def show
  #  @valPoints = valScore
    @pilote = Pilote.all
  end

  # GET /resultats/new
  def new
    @pilote = Pilote.all
    @event = Event.all
    @resultat = Resultat.new resultat_params

  end

  # GET /resultats/1/edit
  def edit
 #   @valPoints = valScore
    @event = Event.all
    @pilote = Pilote.all
    @equipe = Equipe.all
  end

  # POST /resultats or /resultats.json
  def create
    @pilote = Pilote.all
    @equipe = Equipe.all
    @event = Event.all
    @resultat = Resultat.new(resultat_params)

    respond_to do |format|
      if @resultat.save
        format.html { redirect_to resultat_url(@resultat), notice: "Le résultat a bien été créé." }
        format.json { render :show, status: :created, location: @resultat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @resultat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resultats/1 or /resultats/1.json
  def update

  #  @valPoints = valScore
    @pilote = Pilote.all
    @equipe = Equipe.all
    @event = Event.all

    respond_to do |format|
      if @resultat.update(resultat_params)
        format.html { redirect_to resultat_url(@resultat), notice: "Le résultat a bien été mis à jour." }
        format.json { render :show, status: :ok, location: @resultat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @resultat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resultats/1 or /resultats/1.json
  def destroy
    @resultat.destroy

    respond_to do |format|
      format.html { redirect_to resultats_url, notice: "Le résultat a bien été détruit." }
      format.json { head :no_content }
    end
  end


  # test hotwire maj select option
  def pilotes
    @target = params[:target]
    @pilotes = Pilote.get(params[:pilote])

    respond_to do |format|
      format.turbo_stream
    end
  end


  def valScore
    totalScore = 40
  end 

  private


  def formatted_name2
   # "#{id} | #{event_id} | #{pilote_id}"
end



    # Use callbacks to share common setup or constraints between actions.
    def set_resultat
      @resultat = Resultat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def resultat_params
    #  params.require(:resultat).permit(:event_id, :pilote_id, :qualification, :course, :dotd, :mt, :score, :ecurie)

      params.fetch(:resultat, {}).permit(:event_id, :pilote_id, :qualification, :course, :dotd, :mt, :score, :ecurie, :positions)
    
    end




    def valPoints
      if @resultat.course == 1 
         pointsCourse = 25
      else 
        if @resultat.course == 2 
          pointsCourse = 18 
        else 
          if @resultat.course == 3 
            pointsCourse = 15 
          else 
            if @resultat.course == 4 
              pointsCourse = 12 
            else 
              if @resultat.course == 5 
                pointsCourse = 10 
              else 
                if @resultat.course == 6 
                  pointsCourse = 8 
                else
                  if @resultat.course == 7 
                    pointsCourse = 6 
                  else
                    if @resultat.course == 8 
                      pointsCourse = 4 
                    else
                      if @resultat.course == 9 
                        pointsCourse = 2 
                      else 
                        if @resultat.course == 10
                          pointsCourse = 1 
                        else
                          pointsCourse = 0
                        end
                      end 
                    end
                  end 
                end
              end 
            end
          end 
        end
      end 

      if @resultat.dotd == true 
         scoreDotd = 1 
      end 
      if @resultat.mt == true 
         scoreMt = 1 
      end 

      calculAuto = pointsCourse  + scoreDotd.to_i + scoreMt.to_i 
      
      
    end
    
end

app/views/resultats/_form.html.erb
<%= form_with(model: resultat) do |form| %>
  <% if resultat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(resultat.errors.count, "error") %> prohibited this resultat from being saved:</h2>

      <ul>
        <% resultat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% piloteId = form.object.pilote_id %>
  <% if piloteId.nil? %>
  <% else %>
    <% Pilote.find(piloteId).ecurie %>
  <% end %>
  
  <%#<div id="turbo-stream-target">hello </div>%>

  <div data-controller="form-element">
    <%= form.button "Validate", formaction: new_resultat_path, 
        formmethod: :get, data: {turbo_frame: :ecurie_field, 
        form_element_target: "submitbtn"} %>
      <div>
          <%= form.label :pilote_id, style: "display: block" %>
          <%= form.select(:pilote_id, options_from_collection_for_select(
                    @pilote,'id', 'nom',
                    :selected => form.object.pilote_id), 
                    {include_blank: true}, 
                    {data: { action: "change->form-element#remotesubmit"}}) %>
      </div>
  </div>

  <div>
    <%= form.label :event, style: "display: block" %>
    <%= form.select(:event_id, options_from_collection_for_select(
                  @event,'id', 'formatted_name_bis', 
                 :selected => form.object.event_id), 
                 :include_blank => true )%>
 </div>

  <%= turbo_frame_tag :ecurie_field do %>
    <div>

     <% if piloteId.nil? %>
     <% else %>
       <% ecurieLiee = Pilote.find(piloteId).ecurie %>
     <% end %>

      <% form.label :ecurie, style: "display: block" %>
      <%= form.hidden_field :ecurie, value: ecurieLiee %>
    </div>
  <%# end %>
<% end %>

 <div data-controller="form-element">
    <%= form.button "Validate", formaction: new_resultat_path, 
        formmethod: :get, data: {turbo_frame: :score_field, 
        form_element_target: "submitbtn"} %>

      <div>
        <br/>
        <%= form.label :qualification, style: "display: block" %>
        <%= form.select(:qualification, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
                        11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 
                        :selected => form.object.qualification, 
                        :include_blank => true )%>
      </div>
 
      <div>
          <%= form.label :course, style: "display: block" %>
          <%= form.select :course, Resultat.positions, 
          {include_blank: true}, { data: { action: "change->form-element#remotesubmit"}} %>
      </div>

       <div>
          <%= form.label :"Pilote du jour", style: "display: block" %>
          <%= form.check_box :dotd, { data: { action: "change->form-element#remotesubmit"}} %>
      </div>
       <div>
          <%= form.label :"Meilleur tour", style: "display: block" %>
          <%= form.check_box :mt,{ data: { action: "change->form-element#remotesubmit"}} %>
      </div>
  </div>

  <%= turbo_frame_tag :score_field do %>
    <div>

        <% positionCourse = form.object.course %>
        <% if positionCourse.blank? %>
          <% scoreCourse = 0 %>
        <% else %>
          <% if positionCourse == 1 %>
            <% scoreCourse = 25 %>
          <% else %>
            <% if positionCourse == 2 %>
              <% scoreCourse = 18 %>
            <% else %>
              <% if positionCourse == 3 %>
                <% scoreCourse = 15 %> 
              <% else %>
                <% if positionCourse == 4 %>
                  <% scoreCourse = 12 %>
                <% else %>
                  <% if positionCourse == 5 %>
                    <% scoreCourse = 10 %>
                  <% else %>
                    <% if positionCourse == 6 %>
                      <%  scoreCourse = 8 %>
                    <% else%>
                      <% if positionCourse == 7 %>
                        <% scoreCourse = 6 %>
                      <% else%>
                        <% if positionCourse == 8 %>
                          <% scoreCourse = 4 %>
                        <%else%>
                          <% if positionCourse == 9 %>
                            <% scoreCourse = 2 %>
                          <%else %>
                            <% if positionCourse == 10 %>
                              <% scoreCourse = 1 %>
                            <% else %>
                              <% scoreCourse = 0 %>
                            <% end %>
                          <% end %>
                        <% end %>
                      <% end %>
                    <% end%>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>

        <% resultatDotd = form.object.dotd %>
        <% scoreDotd = 0 %>
        <% if resultatDotd == true %>
          <% scoreDotd = 1 %>
        <% end %>

        <% resultatMt = form.object.mt %>
        <% scoreMt = 0 %>
        <% if resultatMt == true %>
          <% scoreMt = 1 %>
        <% end %>
  
        <% scoreTotal = scoreCourse + scoreDotd.to_i + scoreMt.to_i %> 

        <%= form.label :score, style: "display: block" %>
        <%= form.text_field :score, value: scoreTotal %>
      </div>
  <% end %>

  <%# points manuels %>
  <%#= link_to "Points manuels", "", class:"btn btn-outline-danger" %>

<br/>

  <div>
    
     <%= form.submit "Valider", class:"btn btn-success" %>
  </div>
<% end %>

app/views/resultats/_resultat.html.erb
<div id="<%= dom_id resultat %>">
  <p>
    <strong>Event:</strong>
    <%= resultat.event_id %>
  </p>

  <p>
    <strong>Pilote:</strong>
    <% resultat.pilote_id %>
    <%= @pilote = Pilote.find(@resultat.pilote_id).nom %> 
  </p>

  <p>
    <strong>Ecurie:</strong>
      <%= resultat.ecurie %> 
  </p>

  <p>
    <strong>Qualification:</strong>
    <%= resultat.qualification %>
  </p>

  <p>
    <strong>Course:</strong>
    <%= resultat.course %>
  </p>

  <p>
    <strong>DOTD:</strong>
    <% resultat.dotd %>  
      <% if resultat.dotd == true %>
          <i class="fa-solid fa-circle-check fa-xl" style="color:green"></i>
      <% else %>
          <i class="fa-solid fa-circle-xmark fa-xl" style="color:red"></i>
      <% end %>
  </p>
  <p>
    <strong>MeilleurTour:</strong>
     <% resultat.mt %> 
        <% if resultat.mt == true %>
           <i class="fa-solid fa-circle-check fa-xl" style="color:green"></i>
        <% else %>
           <i class="fa-solid fa-circle-xmark fa-xl" style="color:red"></i>
        <% end %>   
  </p>

  <p>
    <strong>Score:</strong>

    <%= resultat.score  %> points

  </p>

</div>

app/views/resultats/edit.html.erb
 <% if user_signed_in? %>
  <% if current_user.admin? %>

    <h1>Editer resultat</h1>

    <%= render "form", resultat: @resultat %>
    <br>

    <div>
      <%= link_to "", @resultat, class:"fa-solid fa-eye btn btn-primary" %> |
      <%= link_to "", resultats_path, class:"fa-solid fa-arrow-rotate-left btn btn-secondary"  %>
    </div>

    <% else %>
    <br/>   <strong>Vous n'avez pas les droits...</strong>
  <% end %>
<% end %>

app/views/resultats/index.html.erb
<% if user_signed_in? %>
    <h1>Resultats</h1>

   <%= render "shared/choixevent" %>

      <% if current_user.admin? %>
          <%= link_to "Nouveau résultat", new_resultat_path, class:"btn btn-primary" %>
          <br/><br/>
      <% end %>

    <% if (@eventId).present? %>
        
      <%= render "shared/eventactif" %>
      
      <%# tableau datas %>
      <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
          <thead class="table-dark">
            <tr>
            <%#   <th>Event</th> %>
            <%#  <th>Pays</th> %>
              <th>Pilote</th>
              <th>Ecurie</th>
              <th>Qualification</th>
              <th>Course</th>
              <th>DOTD</th>
              <th>MT</th>
              <th>Score</th>

              <th colspan="3">Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @resultatsFiltres.each do |res| %>
              <tr>
                <td>  
                    <% idPilote = res.pilote_id %> 
                    <% nomPilote = Pilote.find(idPilote).nom %> 
                    <%= nomPilote %>
                </td> 
                <td> 
                  <% idEcurie = res.ecurie %>  
                  <% nomEcurie = Equipe.find(idEcurie).nom %> 
                  <%= nomEcurie %>
                  <% if Equipe.find(idEcurie).logo.present? %>
                      <%= image_tag Equipe.find(idEcurie).logo, style: "width: 300px; display: block", class: "img-fluid rounded" %>
                  <% end %>
                </td>

              <td class="col_centree"><%= res.qualification %>  </td>
              <td class="col_centree"> <%= res.course %>    </td>

                <td> 
                      <% if res.dotd == true %>
                        <i class="fa-solid fa-circle-check fa-xl" style="color:green"></i>
                      <% else %>
                        <i class="fa-solid fa-circle-xmark fa-xl" style="color:red"></i>
                      <% end %>
                    </td>
                    
                    <td> 
                      <% if res.mt == true %>
                        <i class="fa-solid fa-circle-check fa-xl" style="color:green"></i>
                      <% else %>
                        <i class="fa-solid fa-circle-xmark fa-xl" style="color:red"></i>
                      <% end %>   
                    </td>

                    <%#= points %>
                   <td class="col_centree"> <%= res.score.to_i %>    </td>

                      <%#= actions %>
                      <td class="col_actions">
                          <%= link_to '', res, class:"fa-solid fa-eye btn btn-primary" %> 
                      </td>
                          <% if current_user.admin? %>
                              <td class="col_actions">
                                <%= link_to "", edit_resultat_path(res), class:"fa-regular fa-pen-to-square btn btn-warning" %> 
                              </td> 
                              <td class="col_actions">
                                <%= button_to '', res, class:"fa-solid fa-trash-can btn btn-danger", method: :delete, :onclick => "return confirm('Sûr ?')" %>
                              </td> 
                          <% end %>
              </tr>
            <% end %> 
          </tbody>  
        
        </table>
      </div>
      
      <hr/>

      <%# PDF event actif %>
    
      <% numGp = Event.find(@eventId).numero %>
      <%= link_to "PDF",  resultats_path(saisonId: @saisonId, divisionId: @divisionId, eventId: @eventId, numGp: numGp, format: :pdf), class:"btn btn-dark" %>

    <% end %>

<% else  %>
       <br/>   <strong>Vous n'avez pas les droits...</strong>
<% end %>

app/views/resultats/liste.html.erb
<br>
<h1> Résultats </h1>
<br>

<%# haut de page depuis partial %>
<%= render "shared/hautpdf" %>

  <%#= tableau data classement %>

 <% if (@eventId).blank? %>
 <% else %>
  <% eventNum = Event.find(@eventId).numero %>
    
      <table style="margin-left:auto;margin-right:auto">
        <thead class="table-dark">
          <tr>
            <th class="cols_hide"></th>
            <th>#</th>
            <th>Pilote</th>
            <th>Points</th>
            <th class="cols_hide"></th>
          </tr>
        </thead>

           <tbody>
     <% @resultatsFiltres.each_with_index do | res| %>
     <tr>

         <td>
              <% if res.dotd == true %>
                <%= wicked_pdf_image_tag asset_url('/images/dotd_white.png'), style: "width: 28px; margin-top: 4px;" %>
              <% end %>
           </td>

        <td class="cols_pos_score">
           <strong>  
              <%= res.course %> 
            </strong> 
        </td>

          <td>  
            <div class="contenant">
              <% idPilote = res.pilote_id %> 
              <% idEcurie = res.ecurie %> 
              <% nomPilote = Pilote.find(idPilote).nom %> 
                <%= image_tag Equipe.find(idEcurie).logo, style: "width: 340px; display: block", class: "img-fluid rounded" %>
                      <div class="texte_centrer">
                        <%= nomPilote %>
                      </div>
                  </div>
          </td> 
           <td class="cols_pos_score">
              <strong> <%= res.score.to_i %> </strong> 
           </td>
           <td>
              <% if res.mt == true %>
                 <%= wicked_pdf_image_tag asset_url('/images/mt_white.png'),style: "width: 28px; margin-top: 4px;" %>
              <% end %>
           </td>
        </tr>
      <% end %> 
    </tbody>  
    
  </table>

<%# bas de page depuis partial %>
<%= render "shared/baspdf" %>

<% end %>

app/views/resultats/new.html.erb
<% if user_signed_in? %>
  <% if current_user.admin? %>

    <h1>Nouveau resultat</h1>
    <%= render "form", resultat: @resultat %>
    <br>

    <div>
      <%= link_to "Retour resultats", resultats_path, class:"btn btn-secondary" %>
    </div>

  <% else %>
    <br/> <strong>Vous n'avez pas les droits...</strong>
  <% end %>
<% end %>

app/views/resultats/pilotes.turbo_stream.erb
<%= turbo_stream.update @target do %>
    <%= options_for_select @pilotes %>

  
   
<% end %>

app/views/resultats/show.html.erb
 <% if user_signed_in? %>

    <p style="color: green"><%= notice %></p>

    <%= render @resultat %>

    <div>
        <br/> <hr/>
    
        <%= link_to "", resultats_path, class:"fa-solid fa-arrow-rotate-left btn btn-secondary" %> 

        <% if current_user.admin? %>
            <%= link_to "", edit_resultat_path(@resultat), class:"fa-regular fa-pen-to-square btn btn-primary" %> |
            <%= button_to "", @resultat, class:"fa-solid fa-trash-can btn btn-danger", method: :delete %>
        <% end %>

    </div>

<% else %>
  <br/>
  <strong>Vous n'avez pas les droits...</strong>
<% end %>