config/routes.rb
Rails.application.routes.draw do
  resources :parisbis

  root 'pages#home'

  devise_for :users

  # route pour link to action user admin
  resources :users do
    member do
      get :toggle_status
    end
  end


  resources :friends
  resources :saisons
  resources :divisions
  resources :circuits
  resources :events
  resources :equipes
  resources :pilotes
  resources :resultats
  resources :classecuries
  resources :parieurs


  resources :classements do
    member do
      get :toggle_creerclassements
      get :toggle_updateclassements
      get :toggle_supprimerclassements
      get :toggle_triclassements
    end
  end

  resources :cotes do
    member do
      get :toggle_calculcotes
      get :cote_victoire
    end
  end


  resources :paris do
    member do
      get :toggle_calculresultats
    end
  end

  resources :pariquarts do
    member do
      get :toggle_calculresultats
    end
  end


  get 'home/index'
  get 'home/users'
  get 'home/role'


  # test call action
  resources :licences do
    member do
      get :toggle_creerlicences
      get :toggle_supprimerlicences
      get :toggle_calculrecuplicences
      get :toggle_calculrecuplicencesIndiv
  
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_accueil.html.erb
<br/>
<h2 class="animate__animated animate__bounce">Bienvenue au centre de contrôle de la iF1... !!</h2>
<hr/>

<%= image_tag 'animated_f1.gif', alt: 'icon', width: '40%' %>

<hr/>
 <%#
 <textarea id="textExample">
    Application RoR en developpement
    In code we trust...
  </textarea>
 %>
<script>
    // déclencher js au chargement de la page
    window.addEventListener('load', (event) => {
    animateText(textExample);
    //console.log('page is fully loaded');
    });
</script>

 <%# <button onclick="animateText(textExample)">Relancer</button> %>

 <body>
  <script>
      function animateText(textArea) {
        let text = textArea.value;
        let to = text.length,
          from = 0;

        animate({
          duration: 5000,
          timing: bounce,
          draw: function(progress) {
            let result = (to - from) * progress + from;
            textArea.value = text.substr(0, Math.ceil(result))
          }
        });
      }

  function bounce(timeFraction) {
        for (let a = 0, b = 1; 1; a += b, b /= 2) {
          if (timeFraction >= (7 - 4 * a) / 11) {
            return -Math.pow((11 - 6 * a - 11 * timeFraction) / 4, 2) + Math.pow(b, 2)
          }
        }
      }
  </script>

</body>

app/views/home/_footer.html.erb
<br><hr><br>
<div id="footer">By Scott8ot | in code we trust </small>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <%= link_to image_tag("if1main.png", border: 0, width: 100), root_path, class:"navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span> 
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
         <%#  <li class="nav-item">
      	<%= link_to 'A propos',
      		home_index_path, class:"nav-link" %> 
      

         <% if user_signed_in? %>
            <% if current_user.admin? %>
               <li class="nav-item">
                  <%= link_to 'Saisons', saisons_path, class:"nav-link" %> 
               </li>
               <li class="nav-item">
                  <%= link_to 'Divisions', divisions_path, class:"nav-link" %> 
               </li>
               <li class="nav-item">
                 <%= link_to 'Equipes', equipes_path, class:"nav-link" %> 
               </li>
            <% end %>
           
            <li class="nav-item">
               <%= link_to 'Circuits',
               circuits_path, class:"nav-link" %> 
            </li>
            <li class="nav-item">
               <%= link_to 'Events',
               events_path, class:"nav-link" %> 
            </li>
            <li class="nav-item">
               <%= link_to 'Pilotes',
               pilotes_path, class:"nav-link" %> 
            </li>       
            <li class="nav-item">
               <%= link_to 'Résultats',
               resultats_path, class:"nav-link" %> 
            </li>      
               <li class="nav-item">
               <%= link_to 'Classement Pilotes',
               classements_path, class:"nav-link" %> 
            </li> 
            <li class="nav-item">
               <%= link_to 'Classement Ecuries',
               classecuries_path, class:"nav-link" %> 
            </li>
             <li class="nav-item">
               <%= link_to 'Licences',
               licences_path, class:"nav-link" %> 
            </li>
             <li class="nav-item">
               <%= link_to 'Paris',
               pariquarts_path, class:"nav-link" %> 
            </li>
            <li class="nav-item">
               <%= link_to 'Cotes',
               cotes_path, class:"nav-link" %> 
            </li>
            <li class="nav-item">
               <%= link_to 'Parieurs',
               parieurs_path, class:"nav-link" %> 
            </li>

             <li class="nav-item">
               <%= link_to 'Edit profile',
               edit_user_registration_path, class:"nav-link" %> 
            </li>

               <% if current_user.admin? %>
                  <li class="nav-item">
                     <%= link_to 'Admin', users_path, class:"nav-link text-warning" %>
                  </li>
               <% end %>
                  <li class="nav-item">
                     <%= link_to '', destroy_user_session_path, class:"nav-link fa-solid fa-xl fa-right-from-bracket", 
                        'data-turbo-method': :delete %>
                  </li>
         <% else %>
            <li class="nav-item">
               <%= link_to 'Connexion',
               new_user_session_path, class:"nav-link" %> 
            </li>
            <li class="nav-item">
               <%= link_to 'Inscription',
               new_user_registration_path, class:"nav-link" %> 
            </li>
         <% end %>
    </ul>
  </div>
</nav>

app/views/home/index.html.erb
<br/>
<h2 class="animate__animated animate__bounce">Bienvenue au centre de contrôle de la iF1... !!</h2>
<hr/>

<%= image_tag 'animated_f1.gif', alt: 'icon', width: '40%' %>

<hr/>

 <textarea id="textExample">
    Application RoR en developpement
    In code we trust...
  </textarea>

<script>
    // déclencher js au chargement de la page
    window.addEventListener('load', (event) => {
    animateText(textExample);
    //console.log('page is fully loaded');
    });
</script>

 <%# <button onclick="animateText(textExample)">Relancer</button> %>

 <body>
  <script>
      function animateText(textArea) {
        let text = textArea.value;
        let to = text.length,
          from = 0;

        animate({
          duration: 5000,
          timing: bounce,
          draw: function(progress) {
            let result = (to - from) * progress + from;
            textArea.value = text.substr(0, Math.ceil(result))
          }
        });
      }

  function bounce(timeFraction) {
        for (let a = 0, b = 1; 1; a += b, b /= 2) {
          if (timeFraction >= (7 - 4 * a) / 11) {
            return -Math.pow((11 - 6 * a - 11 * timeFraction) / 4, 2) + Math.pow(b, 2)
          }
        }
      }
  </script>

</body>

app/views/home/users.html.erb
<% @users = User.all %>
<% @admins = User.all.where(role: 2) %>

<br/>

<h2> Liste des admins </h2>
<strong> Nombre: <%= @admins.count %> </strong>

 <div class="table-responsive">
   <table  class="table table-striped table-bordered table-hover">  
    <thead class="table-dark">
      <tr>
        <th> # </th>
        <th> email </th>
       
      </tr>
    </thead>
    <tbody>
      <% @admins.each do |admin| %>
        <tr>
            <td> <%= admin.id %>    </td>
            <td> <%= admin.email %> </td>
           
        </tr>
      <% end %>
    </tbody>
  </table>
 </div>

<br/> <hr/> <br/>

<h2> Liste des membres </h2>
<strong> Nombre: <%= @users.count %> </strong>

 <div class="table-responsive">
   <table  class="table table-striped table-bordered table-hover">  
    <thead class="table-dark">
      <tr>
        <th> # </th>
        <th> email </th>
        <th> Action </th>
    
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
            <td> <%= user.id %>    </td>
            <td> <%= user.email %> </td>


            <td> 
              <% "changer statut" %>
            
              <%= link_to "Passer Admin",  edit_user_path(user), class:"btn btn-dark" %>

            </td>

        </tr>
      <% end %>
    </tbody>
  </table>
 </div>